### for localhost

# FACEBOOK_KEY = 302888333472822
# FACEBOOK_SECRET = 5079f19099de6f31bcc3fb4a192ddf0e

# GOOGLE_ID = 723492048868-0nopn12bvklo5kvam8sd5jhslg0plvts.apps.googleusercontent.com
# GOOGLE_SECRET = eA4dcZmwf0wxu1v8bgOnC3I7

# VK_KEY = 5977552
# VK_SECRET = KQYXAZZhD8oUsNF0FFyi

# ODNOKLASSNIKI_ID = 1250677504
# ODNOKLASSNIKI_SECRET = 3F054B0A1308A826281AB9D6
# ODNOKLASSNIKI_PUBLIC = CBAENMILEBABABABA

### for Heroku

# FACEBOOK_KEY = 340661436395357
# FACEBOOK_SECRET = b78a075a4cdd7d2bbe3c5596d4bc7d01

# GOOGLE_ID = 227077303556-4jud5jkbt15perhbacsju0jclaocqour.apps.googleusercontent.com
# GOOGLE_SECRET = cEg_PxA9K-47Q7DIkzKA1XTe

# VK_KEY = 6234632
# VK_SECRET = exSmSUWZxH66u6EXdUak

# ODNOKLASSNIKI_ID = 1250677504
# ODNOKLASSNIKI_SECRET = 3F054B0A1308A826281AB9D6
# ODNOKLASSNIKI_PUBLIC = CBAENMILEBABABABA

### for All

# AWS_ACCESS_KEY_ID = AKIAISBGT5SYFAYG7MHQ
# AWS_SECRET_ACCESS_KEY = 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



